### ISSUE TITLE
the case of the leaf

### ISSUE THREAD

**Issue by ardubs** [ckolderup/picaro#10]
So I was turning around a short test game idea. I tried to restrict it to one room, no dialogue, and no more than a handful of items. Basically just a single puzzle. 

It goes something like, you're standing in front of a tall tree. There's a single leaf on it. Lying up against the trunk of the tree is a rake. It's clear from your character's perspective that your shining single purpose in this world is to get that leaf off the tree.

Now: someone who's played adventure games before will pick up the rake and use it on the leaf to get it down. Victory! What an amazing performance. 

But: say they went with their first instinct, and just tried to take the leaf. I looked over the wiki and I don't think we have anything in the spec for failure messages specific to items, along the lines of "But you're only four feet tall" in the case of this leaf. 

My proposal, depending on how feasible this is, would be to give items their own noTake property, so that we can acknowledge what the player wants to do -- take the leaf -- and point them in the right direction -- the rake. 

Thoughts? I think it's possible this would be useful as a general-purpose property around all verbs, given that so much of adventure gaming boils down to placing obstacles in front of the player and then hinting at how they might bypass those obstacles.

**Comment by irondavy** [comment]
Makes sense to me!

**Comment by hoverbird** [comment]
Yes, sounds pretty essential to me. This was totally necessary in the pseudo-coded melee island, as well.  Not how we'd actually do it, but it's clear this is very common case:

```
  "name": "Loose Plank",
                "take": {
                    "allowed": false
                },
                "use": {
                    "description": "You step on one end of the loose board, frightening the seagull away",
                    "remove": "Seagull"
                }
            },
           {
                "name": "Fish",
                "take": {
                    "allowed": {
                        "checkAbsenseOf": "Seagull",
                        "failToTake": "The seagull pecks your hand before you can take it"
                    },
                "description": "You pick up the raw fish... are you planning to open a butcher shop?"
                }
            }
```

**Comment by hoverbird** [comment]
I'm going to try to get a working test based on this game running by the end of the weekend.  Will try to get it building IN THA CLOUD so we can all share in it's continue success / periodic failure.

**Comment by ardubs** [comment]
TO THE CLOUD!

As far as I can tell, this consists of:

1 room, the tree ("Its leaves are prized for their medicinal qualities.")

2 items, a rake (can be taken), and a leaf (cannot, hints "You're not tall enough.")

1 victory condition, where the rake (in inventory) is used on the leaf ("Using the leaf, you cure scabies.")

...and that's all she wrote.

**Comment by hoverbird** [comment]
A couple small question arose while implementing this:

1) Clearly you need to be able to use objects you hold (i.e. the rake) on items you don't (the leaf).  I suppose this means we should start listing everything in the room in the Use menu... or maybe we need a property for things that can be Used with being taken? Also curious what @irondavy thinks on this

2) What happens when the game is won? For now I'm just going to display a victory message of the author's choosing, and disable the UI, but we should consider some other UI sugar...

**Comment by hoverbird** [comment]
Ahh, knew I forgot one:

3) What's the interaction flow for using one item on another when you're holding them both?  Currently the "Use" menu will close after the first selection.  Does the player have to open it again, and is the item I already clicked highlighted?

**Comment by JoeBernardi** [comment]
Just now seeing this! The item-specific noTake property was part of the idea all along, and the global one at the top would only be used if the item didn't have one. 

Also, I was assuming that the Use menu wouldn't close after one selection, instead waiting for the player to choose a second item. "Use" listing every usable item in the room makes sense to me.

**Comment by irondavy** [comment]
Yeah, there's an optional second argument for Use (e.g. "Use X" vs. "Use X on Y"). In the design, there's a back arrow in the top left of the Use modal, and that's to step back to choosing the first argument. In the current implementation, that arrow dismisses the modal, but I think we should switch it to my intent in the design. It's my fault for the incorrect implementation, I didn't explain what that was for.

Though, we're still missing a way to decline the optional second argument. One solution would be to make the first choice in the second list something like "(nothing"), so you pick "Use" → "Sword" on → "(nothing)". That wording sucks, but it's a temporary solution.

**Comment by ckolderup** [comment]
Would there be some way to communicate "Sword" and "Sword on..." or "Sword with..." in the first list? That way you could choose the plain ol' "Sword" to get "You swing it through the air wildly" vs "You slay the kobold!"

**Comment by irondavy** [comment]
Not sure I follow the question. Do you mean: can we let the player make the decision on whether they need a second argument before they even pick the first argument?

**Comment by ckolderup** [comment]
Can we offer a decision to the player on the first page? This would be really janky, but might communicate my point— the table cell would be segmented into a left and right half, so it looks something like:

```
| Sword         with... |
| Phone         with... |
| Bread         with... |
```

Or maybe there's some gestural way we could communicate "no, that's it, I'm done, just the one item please."

I'm just trying to think of a way around the clunky "(nothing)" option on the second page.

**Comment by irondavy** [comment]
I'll put some thought into this, I haven't really given it my full attention. I was suggesting the "(nothing)" thing as a fast, temporary solution.

**Comment by hoverbird** [comment]
@JoeBernardi Yep, we definitely still have the notion of takeable and untakeable stuff, with the custom or global message.  Sounds like we're agreed that we should add anything to the Use menu that has the potential for Use with another thing (right now it's just the things you hold).

**Comment by hoverbird** [comment]
I'm starting to think we could do without the "Use on Nothing" feature for v1.  Obviously I can think of cases where folks might want it, since Use is the only general purpose verb (e.g. "use smokebomb" would mean "activate smokebomb", "use door" might mean "open door"). But... I don't think I like the UX backbends that seem necessary to make "Use" work as a unary or binary operator, though.  I'm more in favor of putting the onus on the author to workaround the limitation (like making the smokebomb activate when it's used on _any_ item in the room, or making doors automatically open when unlocked).

Someday we might make things such that you can include only the verbs you want in a game, allowing for special cases that we were depending on Use to catch. If it's a game with tons of things in hidden containers, maybe as an author I want to replace Talk and Attack with Open and Close. Then Use could remain a "Use this on that" action, and have a single UI flow.

**Comment by ardubs** [comment]
Yeah, this makes sense to me, and I'm definitely in favor of keeping
things simple wherever possible -- in v1, and in general. One of my
beefs with Inform is the weird sort of expectation that the player
should be able to do ANYTHING AT ALL, i.e. that because the IF world
model theoretically supports a wide range of actions (using the
smokebomb by itself, throwing it at the wall, throwing it at the
floor, throwing it at your own face, putting it down and stepping on
it, putting it down and throwing a chair at it, etc etc etc ad
infinitum), that every game has to accommodate that range.

Put another way, I am happy and downright enthusiastic to design games
around a more constrained verb set, and would prefer such over
anything that's flexible but complicated to implement.

On Mon, Feb 13, 2012 at 11:06 PM, Patrick Ewing
reply@reply.github.com
wrote:

**Comment by JoeBernardi** [comment]
Makes sense to me, too. I completely agree about designing games around a more constrained verb set. (though if David happens to have some magical UX idea to make it happen, then we might as well go for it).

In some ways I relish the opportunity to release a more restrictive version of Picaro first, just because I imagine it'll result in the creation of way different kinds of games than a future version where all kinds of crazy stuff is possible.

**Comment by ckolderup** [comment]
It sounds frustrating to me, as I can think of any number of interactions involving "using" an object that should have no indirect object, and would never be "important" enough to dedicate an entire custom unary verb out of a limited number of them to the action.

Re: Rob's example, if anything, the binary use case rather than the unary one is what creates the complication in something like Inform, and I think that it's possible that in a future iteration we could eventually get around that by taking more advantage of the fact that we're avoiding a text parser (funnel the list down to only objects that respond to a given verb, for example, if we're not planning on doing that already).

However, the intentionally limited set of interactions thing is something we've discussed all along the way, and I do believe in that leading to interesting results, so I'll go with it for now. I just wanted to be the token person to raise concern for the concept since y'all are way too agreeable.

**Comment by hoverbird** [comment]
I think you raise a few important points, @ckolderup.  For one, I think you're right that there are plenty of actions that won't have an indirect object. We need to consider cases where authors want to specify these interactions, without making things frustrating for the player.

To figure out a balance we should examine how all of the verbs (and their menus) hang together, and make sure we don't get bogged down by pre-touch interfaces like Inform, SCUMM etc.

One reason we're in a rough spot now, I think, is that the Use menu doubles for what would be the Inventory in other systems. In LucasArts games (at least as far back as MI1), you have one Use action that behaves in a Unary way on the world around you, and in a binary way on your Inventory box. Since we have one place to house both, this becomes problematic.

That said, there is a certain elegance to our unified Use menu.  I like that it contains every object currently in view.  Inform will pedantically tell you when you try to, say Use Remote on TV Set, that you must first pick up the remote (or if Emily Short wrote it, it will automatically pick it up for you and tell you so).  I like the idea of Picaro not caring whether you're taking the remote with you or not.

I guess what's really at stake here is the existence of "Use" as a catchall verb. Part of me hates it. Nobody says "use the bacon", they say "eat the bacon". Sometimes I think in the slow process of whittling down the 15 verbs from maniac mansion (remember "fix"?) to the 3 in Full Throttle ("eyes", "mouth", "hands"), the gains in simplicity were offset by the lack of expressiveness.  This might be the point when you just try "using" everything on the screen to see what happens, perhaps.

This is probably a bigger discussion than this thread. In short, I think that Use can work the way it originally was intended if Inventory is separate from Use, I'm just not sure if that's the right direction.

**Comment by irondavy** [comment]
Sorry for my delayed response to this, just getting past the thick of my cross-country move.

My instinct is always to remove things if they're causing problems, so I'm leaning towards removing the unary case. That said, I can think of many cases where it'd be confusing to not have it.

It sounds like the sole challenge is one of usability, not of technology, so I think what we can do is eliminate the unary case for now, and I can work on solving the UX challenges. If I do, or we come up with a more lateral solution, we can revisit at that point.

Hopefully being able to use things on yourself captures a lot of the unary cases like consumables ("use potion") or equippables ("use armor"). It won't capture things like switchable items (lights, machines, electronic objects), open & closable containers, but there are narrative ways to get around those (use power cable on machine, use key on suitcase).

This also means that Attack should have no unary case, which is easier to swallow.

**Comment by hoverbird** [comment]
@david I like this.
