### ISSUE TITLE
Refactor rooms to be more like items

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/picaro#32]
First order of business: split ids for rooms into "id" (the thing that can be used to refer to the room throughout the rest of the script) and "name" (the display label)

Probably some other stuff? Bueller?

**Comment by hoverbird** [comment]
I'm of two minds about this.  I definitely think Rooms and Items should have a _very_ similiar interface.  What I'm less sure about is whether Rooms need to be more like items, or vice versa.  Either way, it's still relatively easy to change the data format, as we don't have THAT many games, and there is decent test coverage of them.  One syntax idea I hope to get comments on is here:

https://gist.github.com/1991571

Thoughts?  Items could potentially work this way, too- keyed by name, with the in-game ability to override the name string without messing up the ID.  If it looks easier to read & write, we can make it work in code without too much trouble, I'm thinking.  I think still need some name-collision-detection code in the editor, either way.

**Comment by ardubs** [comment]
I like this change -- seems easier to read and write from a human perspective, and I think that's worth valuing even once the editor GUI's up and running. Just so I'm clear, in this new syntax does the room also have an ID that can't be changed and a name that can? I only see that top key field in here, so I assume you wouldn't be changing that. I could see adding a field called "displayName" or something, though.

My inclination would be for items to behave more like rooms, since rooms come above items in the hierarchy. Maybe that's an odd reason though.

**Comment by hoverbird** [comment]
Joe- agreed.  Edited this example to have items mirror rooms, in both cases. Maps on top, Lists on bottom.

Also made it so neither requires an ID.  I think all the arguments for a super-easy to write data format are strong, and the general case for picaro is for smaller games.  Name collisions are less of a problem then, and we can use the editor / game-checking scripts to ensure unique names, I think.

**Comment by hoverbird** [comment]
...and by joe, I clearly meant rob. That's dysnomia for you.

So yeah, not to confuse the issue, but regardless of nesting syntax, I think I've seen the light on mandatory IDs. We can be more clever in the player and editor code and keep the data format simpler as a result, and I think that's worth it. I like everyone's dedication to keeping the data format lightweight and easy to read/write, and i think that means doing away with any requirements in the format that don't convey information to humans, unless absolutely necessary for the game to be playable.

**Comment by ckolderup** [comment]
Now I'm confused. So we're not going with separate ids and display names? I found it annoying that any time I wanted to have a descriptive room name I had to repeat that in all path objects that referred to it and if it had any sort of special characters I frequently had to make it a quoted string and I dunno it just seemed very counterintuitive to me but maybe that's just because i'm thinking too much like a programmer.

**Comment by hoverbird** [comment]
@ckolderup Good questions! I think since I'm only thinking on Picaro on late nights, my communication skills are worn down from interfacing with machines and product managers all day.  Apologies for the confusion.

What I'm suggesting: defining object IDs object IDs in your game file is optional. BUT it would be encouraged for larger/more complex games (for reasons I'll explain below).

Behind the scenes, when we parse the game data, any YAML object without an "id" will have its "name" property copied into it's "id" property.  So, all objects still have IDs, and that's how we reference between objects (i.e. an item's location, where a path leads to etc.)   IDs are unique and immutable, and they will be untouched even if the "name" property is changed during the course of a game.

This also means that, if you choose the lightweight "reference by name" style in your game file, your room/item names will also need to be unique.  If you explicitly set IDs, then having duplicate names won't be a problem.

We'll offer some sort of automatic validation mechanism (could be a simple script to start, and part of a full-fledged editor eventually) to ensure that your IDs are unique (YAML validation actually provides this to a limited degree- within an object, all keys must be unique to be valid YAML).

**Comment by ckolderup** [comment]
Okay, that sounds good to me. Thanks. :)

**Comment by JoeBernardi** [comment]
Ohh! I was also confused, but Patrick's explanation makes a lot of sense. Being able to opt into or out of having heavy-duty ID's sounds really good, yeah. Woo.

**Comment by hoverbird** [comment]
Phew! Changing all that kicked up a lot of dust, but I'm happy to say all the tests are passing again.  Rooms and Items should be much more consistent now, and the syntax is a bit less demanding.  Let me know if anyone spots any bugs (we should probably deploy to Heroku for testing, if folks are cool with that).  I'll get to work on documenting the YAML format as it stands today.
