### ISSUE TITLE
The demo game is broken

### ISSUE THREAD

**Issue by hoverbird** [ckolderup/picaro#5]
I know this was only recently thrown up on the web, so I'm not sure what used to work and what's just unimplemented. Some things work great, but many don't- and this half-broken state is hard to develop on.  Before we add more things to the JSON spec, it's probably best to get the basic example code runnable end-to-end.

If we do, I'll set up a build process with [Travis CI](http://travis-ci.org) so that we can know if pushes to the repo are breaking any example games.  I don't know if you remember but the Inform creation tool had a test runner built into it, to make finding breaking changes and edge cases in your games easier.  That was necessary given the complexity of Inform, but also a huge wart for people new to software development. It shouldn't have been there.

So, I'd like to see Picaro have a goal that games created through the GUI are **impossible to break**. If we can set up an automated test suite early on, it might just make that goal achievable.

**Comment by irondavy** [comment]
Yeah, I asked Joe to push code I knew to be broken so that I could work on the UI. We might be talking about what to build in the future, but the target is still the 1.0 spec which is what we're trying to finalize by exploring the limits of what we have. Revising dialog, for example.

What's the next action you're recommending here? Producing a full 1.0 spec? We're still a ways away from having the builder GUI.

**Comment by hoverbird** [comment]
The Builder GUI vs. the capabilities of a game it produces is a really interesting chicken and egg problem.  Obviously you want to explore the space of what's possible in these games, but at the same time constraining that space to what can be simply expressed through the editor.  I like that so far you guys have been inching them both forward in tandem, and I think that's the right way to proceed.

When I give it some thought, I'm advocating for starting with a few simple, working games _instead of_ a JSON spec. This might be my "agile" alignment, but I think that runnable examples (often called specs) are better than comprehensive documentation. Documentation is great too, but it doesn't break when the code changes- it just becomes misleading.

The constraint for updating the "spec games" would be that we don't add anything that we haven't figured out how to express in the editor.  This way you can continue the evolution of game capability + editor functionality in a back and forth, incremental way, without waiting for a Bill of JSON Rights to be ratified.

If you like the idea, the next step for me would be to set up a a test suite that "plays" through hmm.json and verifies that, from a player perspective, nothing is broken. We would then display the build status on the Picaro github page, and could als set up hipchat hooks to announce when things go red.

**Comment by hoverbird** [comment]
Addendum: a v 1.0 feature spec still makes a ton of sense.  "A player can pick up items; use items on other items; use items on themselves ..." sort of thing will be a great way to scope things and move features above or below the 1.0 line.  I just don't think it's as helpful to define that in terms of what the JSON data will look like.

**Comment by ardubs** [comment]
I think what you're saying fits with the fact that I've mostly been developing off the source for hmm.json, since I know that Joe's only implementing things that he knows will work in the player prototype.

**Comment by irondavy** [comment]
This all makes sense to me. It sounds like we have three moving parts:
- The feature spec for 1.0
- Test game for 1.0
- Test suite for 1.0

I've updated the wiki spec to be a "feature" spec rather than a "JSON" spec. As far as I can tell, it's complete — at least in terms of the what (but not the how).

It seems like we might benefit from giving the task of creating a test game to someone who isn't working on the parser itself, to help avoid blindspots. @ardubs would you be interested in this?

Once we have the game, @hoverbird can create the test suite? Am I wrapping my head around this correctly?

**Comment by hoverbird** [comment]
Sounds good to me. @ardubs can either iterate on hmm.js or start fresh, working with @JoeBernardi and myself to implement missing pieces / chase down bugs.  The first tests I'll add will be integration tests- basically driving a browser to click through a game session via its web interface.

We'll shoot for a 1:1 relationship between the V1 feature spec and test cases in the suite- ideally any functionality we spec out in the former will be exercised in the latter.
